### ISSUE TITLE
CDM error

### ISSUE THREAD

**Issue by Dcmq** [DevLARLEY/mpdl#3]
When i select cdm files, in command prompt shows an error 
No such file or derectory 'data/pywidevine/L3/cdm/devices/android_generic/'

**Comment by DevLARLEY** [comment]
did you select both files (hold STRG)?
are you running mpdl from the path it is in? (what directory did you run 'python3.12 mpdl.py' from?)

**Comment by Dcmq** [comment]
Thank you very much
Browser cannot play drm mpd videos
It says "firefox is installing components to play audio and video try again later.."

**Comment by Dcmq** [comment]
Not opening browser

**Comment by Dcmq** [comment]
Sorry for disturbing...
I try to download selecting mpd it shows an unknown error(without selecting lisence url)
It says MPDL error

**Comment by Dcmq** [comment]
![Uploading 20240215_211223.jpg…]()

**Comment by DevLARLEY** [comment]
i'm so sorry, i forgot to include the main data folder in the github repo. i'll add it soon
i also updated requirements.txt, so be sure to install the changes.

**Comment by DevLARLEY** [comment]
i updated the files. it should work now

**Comment by Dcmq** [comment]
I try with new verson and try download selecting mpd and lisence url..but it shows and error "unable to parse license- check protobufs"

**Comment by Dcmq** [comment]
![20240216_181100](https://github.com/DevLARLEY/mpdl/assets/160096974/e200f327-f241-41ae-b435-e8269da32a79)

**Comment by DevLARLEY** [comment]
could you post the mpd url?

**Comment by Dcmq** [comment]
https://video.lk.databoxtech.com/manifest/7TPHNPXGTNNVQNZZ/94717201780/1708099773/f12dc9b4f30373381fde35fd99f0995c/sisulka/.mpd

**Comment by DevLARLEY** [comment]
i'm getting a 401 error "Sorry you are not allowed to view this video!" even with a different ip. are you getting the same message? if not, could you upload the file?

**Comment by DevLARLEY** [comment]
that's a very interesting link. it doesn't redirect you to the .mpd file but rather you land on an html page. if you  go into the network tab, you'll see .mpd file being "received". you can download it from there by double clicking on the url. that's also the reason why yt-dlp and my program (requests and urllib.request) error out. so you'd have to extract the pssh manually (AAAAhHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAGQSEOGroA46tUijkUKr4scwhGoaJDNiYzgxMmUwLTNhNzQtNGE5NC04NmY4LWQ0NjlhNTBlNDM0NiIkZTFhYmEwMGUtM2FiNS00OGEzLTkxNDItYWJlMmM3MzA4NDZhSOPclZsG), which won't help you because yt-dlp will still crash and i don't know how yt-dlp locates the video files using an mpd file.

update: for this file, the video and audio links are actually inside of the mpd file

**Comment by Dcmq** [comment]
Thank you very much for helping 
Yes it is. I can download video and audio but cannot be played.
They are encrypted... need be decrypted the files and merge
Actually i dont know much about this field
It is like the site require specific json-formatted data in the lisence request 
Could you tell me a way to download this kind of videos please

**Comment by DevLARLEY** [comment]
i could try to get the keys if i had a license url and request headers

**Comment by Dcmq** [comment]
Lisence url = https://licensing.eduvid.lk/acquireLicense/widevine
Request headers= dont know i think POST

Please give a try

**Comment by DevLARLEY** [comment]
the licensing server is giving me a "Misusing attempt detected" so i need the request headers:
right click the license url: 
on firefox do: Copy Value --> Copy as cURL (POSIX)
on chrome do: Copy --> Copy as cURL (bash)
